# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Morteza Motegh
tagline:          'A Jekyll theme'
description:      'Data Science Business Analyst'
url:              http://tezamo.github.io
baseurl:          

author:
  name:           'Tezamo'
  url:            https://twitter.com/tezamo

paginate:         5
paginate_path: "/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tezamo

plugins:
  - jekyll-paginate
  - jekyll-gist

# Markdown configuration
kramdown:
  input: GFM
  parse_block_html: true
  parse_span_html: true