# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Morteza Motegh
tagline:          'A Jekyll theme'
description:      'Data Science Business Analyst'
url:              http://tezamo.github.io
baseurl:          /

author:
  name:           'Tezamo'
  url:            https://twitter.com/tezamo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tezamo
