source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"       
gem "webrick", "~> 1.7"       
gem "csv"
gem "logger"
gem "base64"
gem "jekyll-paginate"
gem "jekyll-gist"
gem "kramdown", "~> 2.0"
gem "rouge", "~> 4.0"
